export { default as AboutIntroduction} from './AboutIntroduction/AboutIntroduction'
export { default as About} from './About/About'
export { default as Advantages} from './Advantages/Advantages'
export { default as Hardworking} from './Hardworking/Hardworking'
export { default as OurTeam} from './OurTeam/OurTeam'